### ISSUE TITLE
Expose a variant of `connect` that takes offset and length as argument

### ISSUE THREAD

**Issue by reynir** [reynir/mirage-block-partition#6]
The current `connect` interface has the nice property that it is difficult to create overlapping partitions. However, in the context of Mirage the Functoria API doesn't have a concept of pairs. It is not clear to me how or if the current interface can be integrated into the Mirage tool.

Implement a variant of `connect` (could be named `connect'`) that takes and offset and a length and returns a single partition.

**Comment by 0xrotense** [comment]
can i work on this?

do i write the code to this file https://github.com/reynir/mirage-block-partition/blob/main/lib/mirage_block_partition.ml ? or as a comment here ?

**Comment by reynir** [comment]
Yes, you may work on this. It would be great if you could submit it as a pull request. You need to update lib/mirage_block_partition.ml but as well the interface file lib/mirage_block_partition.mli to expose the new function.

**Comment by AryanGodara** [comment]
@reynir , are there more issues coming for mirage-block-partition, or can everyone try this issue first?

**Comment by reynir** [comment]
> @reynir , are there more issues coming for mirage-block-partition, or can everyone try this issue first?

If you like you can work on this issue

**Comment by AryanGodara** [comment]
> > @reynir , are there more issues coming for mirage-block-partition, or can everyone try this issue first?
> 
> If you like you can work on this issue

Thanks @reynir , I'll go open a PR, when ready!

**Comment by reynir** [comment]
@AryanGodara I would look at the definitions of `connect`, `subpartition` and `partition` as they do something similar.

**Comment by AryanGodara** [comment]
> @AryanGodara I would look at the definitions of `connect`, `subpartition` and `partition` as they do something similar.

Got it!
Thanks @reynir , I'll start work on this first thing tomorrow morning!

**Comment by 0xrotense** [comment]
@reynir ,  I just updated the PR, kindly review and advise further. Thanks

**Comment by 0xrotense** [comment]
@reynir please check my new comment on my PR, to advise further. thanks

**Comment by reynir** [comment]
@0x0god You are welcome to keep working on this. Note however that the Outreachy contribution period is over and further contributions will not be considered for you application. I will as well have less time to help and guide you. So expect to be more self-reliant if you want to continue working on this.

**Comment by 0xrotense** [comment]
Thanks,...Yes, I understand the outreachy contribution period is over :)

I'm doing this personally to improve my OCaml skills as I develop a passion for OCaml and also to contribute more to the opensource community. :)
