### ISSUE TITLE
`Mirage_block_partition.disconnect` should not call `disconnect` on the underlying block device

### ISSUE THREAD

**Issue by reynir** [reynir/mirage-block-partition#8]
Calling `disconnect` on a partition calls `disconnect` on the underlying partition. This is not a good idea since the block device might be used by another partition for example.

https://github.com/reynir/mirage-block-partition/blob/ef87c5a5468a4520fa855987eb405d9da33cf818/lib/mirage_block_partition.ml#L85-L87

**Comment by dianaoigo** [comment]
@reynir just a thought, how about specifying a partition and block device to be disconnected without affecting any other partitions using same block device? Kindly bear with me if am wrong.

**Comment by dianaoigo** [comment]
@reynir alternatively, would it be possible to check and provide an alert if there is a block device connected to the underlying partition before disconnecting

**Comment by dianaoigo** [comment]
@reynir i was stuck om the other issue you assigned me and you've been missing in action to help but it's okay. Therefore, i decided to look into issue #15 and so far the code below is what i have so far. any comments

[https://github.com/dianaoigo/mirage-block-partition](url)
  let disconnect b =

    (* XXX disconnect both?! *)
     b.attached <- false;
     Lwt.return_unit
    B.disconnect b.b
end

**Comment by reynir** [comment]
Hi @dianaoigo, please do not expect me to be available in the weekend.

You have some good questions and ideas. Unfortunately, I don't think we can keep track of what other devices may still be using the underlying block device.

The type would need extending with a field `attached` which tracks the attached state of the partition. This state would need to be checked in the various operations (read, write, ..).

You can open a (draft) pull request with your changes so we more easily can review the changes. Make sure it builds and the tests pass (`dune build` and `dune runtest`).

**Comment by dianaoigo** [comment]
@reynir i have been playing around around with some conditional statements but  on running test some don't pass. Am i allowed to write tests for my particular use case?

**Comment by reynir** [comment]
Yes! Writing new tests is encouraged

**Comment by dianaoigo** [comment]
@reynir  i am having issues pushing changes. 
ERROR: Permission to reynir/mirage-block-partition.git denied to dianaoigo.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by dianaoigo** [comment]
@reynir there's an issue i have been experiencing the issue of
 Error: Version 3.4 of dune is not supported.
Supported versions:
- 1.0 to 1.12
- 2.0 to 2.1
This is on ubuntu 20. should i raise the issue? so far dune 2.1 works just fine. maybe it can be added in the documentation

**Comment by reynir** [comment]
How do you observe that error? How is it triggered? Is there more output?

I have not observed this error before.

**Comment by dianaoigo** [comment]
@reynir after forking and cloning the repo, upon attempting to run dune build or installing the dependencies that's the error that's thrown.  All i did was edit the dune version and after was allowed to proceed. I actually attempted the same on three different ubuntu machines and the error was the same. No, there is no more output, just that version 3.4 was not supported.

**Comment by reynir** [comment]
Is the error similar to this? Save for the specific version numbers https://stackoverflow.com/questions/57594205/dune-version-not-supported

**Comment by dianaoigo** [comment]
@reynir yes, . except this one specified dune 3.4..

**Comment by reynir** [comment]
Ok, then there was more output than what you pasted.

You can install the dependencies with expected versions by running this in the directory: `opam install --deps-only --with-test .` This will read the .opam file and install all dependencies including those used for running the tests.

**Comment by dianaoigo** [comment]
@reynir there wasn't any. i infact have the screenshot. I can e-mail it to you

**Comment by dianaoigo** [comment]
@reynir funny thing is the command opam install --deps-only --with-test  doesn't work either. dune external-lib-deps --missing @@default is what works on ubuntu

**Comment by dianaoigo** [comment]
@reynir here is a funny behavior, that error is only thrown after cloning. change the dune version to 2.1 or below, install dependencies and once you can successfuly build, now reverting the dune version to 3.4 has no effect whatsoever. absolutely hilarious

**Comment by pitag-ha** [comment]
Hi @dianaoigo, nice to see that you seem very engaged in contributing! 

> that error is only thrown after cloning.

Do I understand correctly that you know how to solve the set-up problem now? Or do you need more help with it?

**Comment by dianaoigo** [comment]
@pitag-ha  i already figured it out. Was just wondering if it needed to be raised or documented for future use. I actually tried it on three different machines before consulting if maybe it needed to be raised as an issue.

**Comment by dianaoigo** [comment]
@pitag-ha i could use some help on a separate issue on ppxlib can i tag you on it?

**Comment by pitag-ha** [comment]
It's ok to ping me, yes.

**Comment by 0xrotense** [comment]
can I work on this, please?

**Comment by dianaoigo** [comment]
@0x0god i have been working on this issue and even submitted a pull request for review. Kindly check with the mentors first

**Comment by 0xrotense** [comment]
> @0x0god i have been working on this issue and even submitted a pull request for review. Kindly check with the mentors first

okay good, that's fine.

**Comment by dianaoigo** [comment]
@reynir i've pushed new changes based on recommendations, kindly review them and advise.

**Comment by dianaoigo** [comment]
@reynir while i am still working on the latest changes, I am expected to make application to the project on the outreachy page. there's a part that requires i consult with you. 
Please work with your mentor to provide a timeline of the work you plan to accomplish on the project and what tasks you will finish at each step. Make sure take into account any time commitments you have during the Outreachy internship round. If you are still working on your contributions and need more time, you can leave this blank and edit your application later.  Kindly provide suggestions on what to fill for to satisfy the part(timeline of the work you plan to accomplish on the project and what tasks you will finish at each step)

**Comment by reynir** [comment]
@dianaoigo the timeline is an overview of what tasks you want to work on and an estimate of how long each (sub) task takes. I can't tell you what you are interested in working on. If you have a draft of a timeline I can review it and make comments, and I can answer questions you might have about the proposed intern tasks in the project description.

**Comment by dianaoigo** [comment]
the project i am applying to is titled: Persistent storage in MirageOS
and the tasks: 
- Write example unikernel(s) using partition tables and file systems. As a base a repository for block device partitioning exists: https://github.com/reynir/mirage-block-partition
- Improve MBR support and integrate mbr “devices” into the Mirage tool. Rewrite example unikernels with the now built-in devices.3
- Implement GPT (GUID Partition Table). Existing work exists that can be used to build an implementation on top of. This can be skipped.
- Update the FAT implementation and fix bugs. The implementation assumes properties that are only valid for the Xen backend and can lead to bugs, and has suffered from bitrot.
- Implement a swap-like abstraction on top of a block device to keep track of temporary allocations.
- Use the above swap-like abstraction with the read/write tar implementation to allow downloading archives and writing them to the filesystem only if they match a checksum. All in a streaming fashion. 
I genuinely am lost on this one. It's easier when there is an issue to solve or raise. do u have access to what earlier interns wrote that i can use as a guide?

**Comment by reynir** [comment]
I don't have access to earlier interns' applications. I suggest you pick a few tasks you think sound interesting, divide them into smaller sub tasks and then assign the number of weeks you expect each sub task will take to complete. It is hard to estimate time spent on tasks in computing, so don't worry too much about the accuracy of the estimate.

If you have questions about the tasks don't hesitate to ask them.
